### ISSUE TITLE
Possibly supporting other screenshotting utilities besides maim?

### ISSUE THREAD

**Issue by woodruffw** [JSchilli1/poomf.sh#4]
Would you be interested in poomf.sh supporting other screenshotting utilities via a conditional check?

I didn't want to install `maim`, so I modified your script to work with my setup:
https://github.com/woodruffw/dotfiles/blob/master/scripts/poomf.sh

If you'd like me to commit that sort of functionality, I'd be happy to.

Best,
William

**Comment by JSchilli1** [comment]
Thanks for asking. For now, download the newest version and replace the 'maim' function with your preferred screenshot program. It's a little inflexible, because the -s option just adds '-s' to maim, but I'll working on improving that. Perhaps I'll add fscreen and sscreen variables that will be executed by their respective options.

**Comment by woodruffw** [comment]
Alright.

Thanks for the quick reply!

**Comment by JSchilli1** [comment]
Fixed, please edit fscreen and sscreen with the commands for your preferred screenshot utility!

**Comment by woodruffw** [comment]
Cool, thanks.
